spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123
    url: jdbc:mysql://192.168.88.175:3306/SpringCloud_Sell?characterEncoding=utf8&useSSL=true
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.88.175
    port: 5672
    username: root
    password: root
  redis:
    host: 192.168.88.175
    port: 6379
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
server:
  port: 7001
env: dev
girl: 
  name: lili
  age: 19
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
